import type { MetadataRoute } from 'next'

// Web App Manifest (served at /manifest.webmanifest). Generated by Next so it
// stays in sync with the app. theme_color matches the dark mobile top bar /
// sidebar; background_color matches the app canvas (used for the splash screen).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Obra Creative Media Productions',
    short_name: 'Obra CMP',
    description:
      'Internal management system for Obra Creative Media Productions — College of Computer Studies, Dominican College of Tarlac.',
    id: '/dashboard',
    start_url: '/dashboard',
    scope: '/',
    display: 'standalone',
    background_color: '#F7F7F5',
    theme_color: '#0D0D0D',
    lang: 'en',
    dir: 'ltr',
    categories: ['productivity', 'business'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
